import type { Config } from 'tailwindcss';

const config = {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1f',
        'on-tertiary-fixed-variant': '#005228',
        'outline-variant': '#c4c6cd',
        error: '#ba1a1a',
        'secondary-fixed': '#6bfe9c',
        'surface-container-highest': '#e1e2e6',
        'on-tertiary-fixed': '#00210c',
        'surface-container': '#eceef1',
        'surface-container-low': '#f2f4f7',
        'secondary-fixed-dim': '#4ae183',
        'on-primary-fixed-variant': '#38485a',
        'error-container': '#ffdad6',
        'surface-tint': '#4f6073',
        'primary-container': '#1a2b3c',
        'on-primary-container': '#8192a7',
        'inverse-surface': '#2e3134',
        'on-secondary-container': '#00743a',
        'on-surface-variant': '#44474c',
        primary: '#041627',
        'surface-dim': '#d8dade',
        'tertiary-fixed': '#6bfe9c',
        tertiary: '#001a08',
        'surface-variant': '#e1e2e6',
        'secondary-container': '#6bfe9c',
        secondary: '#006d37',
        'inverse-on-surface': '#eff1f4',
        'primary-fixed-dim': '#b7c8de',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#4ae183',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        background: '#f8f9fd',
        'on-error': '#ffffff',
        outline: '#74777d',
        'on-primary-fixed': '#0b1d2d',
        'on-tertiary-container': '#00a656',
        'on-secondary-fixed-variant': '#005228',
        'inverse-primary': '#b7c8de',
        'primary-fixed': '#d2e4fb',
        'on-surface': '#191c1f',
        'tertiary-container': '#003115',
        surface: '#f8f9fd',
        'on-secondary-fixed': '#00210c',
        'on-secondary': '#ffffff',
        'surface-container-high': '#e6e8ec',
        'surface-bright': '#f8f9fd',
      },
      fontFamily: {
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
} satisfies Config;

export default config;
